name: Build SATySFi Documents

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build PDFs and index using Docker
        run: |
          mkdir -p ${{ github.workspace }}/public && docker run --rm -v ${{ github.workspace }}:/workspace amutake/satysfi:latest \
            sh -c "cd /workspace/projects && \
                  find . -name '*.saty' | while read file; do \
                    base=\$(basename \"\$file\" .saty); \
                    satysfi \"\$file\" -o \"/workspace/public/\$base.pdf\";
                  done"

      - name: Copy website sources
        run: cd ${{ github.workspace }}/src && cp ./* ${{ github.workspace }}/public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
